packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@firebase/util'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - core-js
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
